name: (Auto) Deploy to Dev

on:
  pull_request:
    types: [closed]
    branches: [ main ]

env:
  REGISTRY: registry.cn-beijing.aliyuncs.com  # 替换为你的私有镜像仓库地址
  IMAGE_NAME: dobbinsoft/${{ github.event.repository.name }}
  NAMESPACE: gus-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure Maven Settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <mirrors>
                  <mirror>
                      <id>mirror</id>
                      <mirrorOf>central,jcenter,!rdc-releases,!rdc-snapshots</mirrorOf>
                      <name>mirror</name>
                      <url>https://repo.maven.apache.org/maven2</url>
                  </mirror>
              </mirrors>
              <servers>
                  <server>
                      <id>rdc-releases</id>
                      <username>${{ secrets.RDC_USERNAME }}</username>
                      <password>${{ secrets.RDC_PASSWORD }}</password>
                  </server>
                  <server>
                      <id>rdc-snapshots</id>
                      <username>${{ secrets.RDC_USERNAME }}</username>
                      <password>${{ secrets.RDC_PASSWORD }}</password>
                  </server>
              </servers>
              <profiles>
                  <profile>
                      <id>rdc</id>
                      <properties>
                          <altReleaseDeploymentRepository>
                              rdc-releases::default::https://packages.aliyun.com/maven/repository/2084582-release-15hIVc/
                          </altReleaseDeploymentRepository>
                          <altSnapshotDeploymentRepository>
                              rdc-snapshots::default::https://packages.aliyun.com/maven/repository/2084582-snapshot-Vrq4iK/
                          </altSnapshotDeploymentRepository>
                      </properties>
                      <repositories>
                          <repository>
                              <id>central</id>
                              <url>https://repo.maven.apache.org/maven2</url>
                              <releases>
                                  <enabled>true</enabled>
                              </releases>
                              <snapshots>
                                  <enabled>false</enabled>
                              </snapshots>
                          </repository>
                          <repository>
                              <id>snapshots</id>
                              <url>https://repo.maven.apache.org/maven2</url>
                              <releases>
                                  <enabled>false</enabled>
                              </releases>
                              <snapshots>
                                  <enabled>true</enabled>
                              </snapshots>
                          </repository>
                          <repository>
                              <id>rdc-releases</id>
                              <url>https://packages.aliyun.com/maven/repository/2084582-release-15hIVc/</url>
                              <releases>
                                  <enabled>true</enabled>
                              </releases>
                              <snapshots>
                                  <enabled>false</enabled>
                              </snapshots>
                          </repository>
                          <repository>
                              <id>rdc-snapshots</id>
                              <url>https://packages.aliyun.com/maven/repository/2084582-snapshot-Vrq4iK/</url>
                              <releases>
                                  <enabled>false</enabled>
                              </releases>
                              <snapshots>
                                  <enabled>true</enabled>
                              </snapshots>
                          </repository>
                      </repositories>
                      <pluginRepositories>
                          <pluginRepository>
                              <id>central</id>
                              <url>https://repo.maven.apache.org/maven2</url>
                              <releases>
                                  <enabled>true</enabled>
                              </releases>
                              <snapshots>
                                  <enabled>false</enabled>
                              </snapshots>
                          </pluginRepository>
                          <pluginRepository>
                              <id>snapshots</id>
                              <url>https://repo.maven.apache.org/maven2</url>
                              <releases>
                                  <enabled>false</enabled>
                              </releases>
                              <snapshots>
                                  <enabled>true</enabled>
                              </snapshots>
                          </pluginRepository>
                          <pluginRepository>
                              <id>rdc-releases</id>
                              <url>https://packages.aliyun.com/maven/repository/2084582-release-15hIVc/</url>
                              <releases>
                                  <enabled>true</enabled>
                              </releases>
                              <snapshots>
                                  <enabled>false</enabled>
                              </snapshots>
                          </pluginRepository>
                          <pluginRepository>
                              <id>rdc-snapshots</id>
                              <url>https://packages.aliyun.com/maven/repository/2084582-snapshot-Vrq4iK/</url>
                              <releases>
                                  <enabled>false</enabled>
                              </releases>
                              <snapshots>
                                  <enabled>true</enabled>
                              </snapshots>
                          </pluginRepository>
                      </pluginRepositories>
                  </profile>
              </profiles>
              <activeProfiles>
                  <activeProfile>rdc</activeProfile>
              </activeProfiles>
          </settings>
          EOF

      # build to jar
      - name: Build with Maven
        run: |
          mvn package
          ls

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Replace Dockerfile
        run: |
          sed -i "s/\${REPO_NAME}/${{ github.event.repository.name }}/g" Dockerfile

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          provenance: false      # 禁用安全证明
          sbom: false            # 禁用软件物料清单
          platforms: linux/amd64 # 明确指定单架构
          load: false            # 确保不产生本地加载
          outputs: type=image,push=true # 强制标准镜像输出
      - name: Set up Kubernetes Context
        if: github.ref == 'refs/heads/main'
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          
      - name: Replace variables in deployment.yaml
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s/\${NAMESPACE}/${{ env.NAMESPACE }}/g" k8s/deployment.yaml
          sed -i "s/\${APP_NAME}/${{ github.event.repository.name }}/g" k8s/deployment.yaml
          sed -i "s|\${IMAGE}|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml
          
      - name: Deploy Application to Kubernetes
        if: github.ref == 'refs/heads/main'
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          namespace: ${{ env.NAMESPACE }}
          args: --validate=false
          action: deploy
          strategy: none